version: '2'

tasks:
  go:
    cmds:
      - protoc --go_out=plugins=grpc,import_path=workflowproto:go workflowproto/*.proto
  node:
    cmds:
      - grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./nodejs/lib --grpc_out=./nodejs/lib --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` workflowproto/*.proto

