version: '2'

tasks:
  go:
    cmds:
      - protoc --go_out=plugins=grpc,import_path=workflowproto:go workflowproto/*.proto
  node:
    cmds:
      - grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./nodejs/lib --grpc_out=./nodejs/lib --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` workflowproto/*.proto
      - protoc --plugin=protoc-gen-ts=./nodejs/node_modules/.bin/protoc-gen-ts --ts_out=./nodejs/lib workflowproto/*.proto
      # - protoc --plugin="protoc-gen-ts={{.PROTOC_GEN_TS_PATH}}" --js_out="import_style=commonjs,binary:{{.OUT_DIR}}" --ts_out="service=true:{{.OUT_DIR}}" workflowproto/*.proto
    vars:
      OUT_DIR: "./nodejs/lib"
      PROTOC_GEN_TS_PATH: "./nodejs/node_modules/.bin/protoc-gen-ts"
  clean:
    deps:
      - clean-node

  clean-node:
    cmds:
      - rm ./nodejs/lib/workflowproto/*.js

        

